{% set name = "invariant-point-attention" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/invariant-point-attention-{{ version }}.tar.gz
  sha256: e741679369119e42019bb134a6609e1a8cd1c40451cf9e1f768bc5600af02856

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner
    - pip
  run:
    - python >=3.6
    - einops >=0.3
    - pytorch >=1.7

test:
  imports:
    - invariant_point_attention
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lucidrains/invariant-point-attention
  summary: Invariant Point Attention
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdblischak
    - eliottpark
